FROM ruby:2.3.1-alpine
ENV RAILS_ENV=development
RUN apk add --no-cache --update mariadb-dev tzdata nodejs && \
    apk add --no-cache --virtual build-dependencies \
    git \
    build-base \
    libxml2-dev \
    libxslt-dev \
    less \
    curl
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
WORKDIR /app
RUN bundle install
CMD ["ash"]
