version: '2'
services:
  dios-database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dios:/var/lib/mysql
    networks:
      - dios
  dios-application:
    build: .
    image: dios-application
    environment:
      - DIOS_PORT=3000
      - DIOS_DATABASE_HOST=dios-database
      - DIOS_DATABASE_USER=root
      - DIOS_DATABASE_PASSWORD=root
      - DIOS_SECRET_KEY_BASE=1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
      - DIOS_KONG_URL=http://kong-application:8001
      - CUENTA_DATABASE_HOST=cuenta-database
      - CUENTA_DATABASE_USER=root
      - CUENTA_DATABASE_PASSWORD=root
      - ALDEA_DATABASE_HOST=aldea-database
      - ALDEA_DATABASE_USER=root
      - ALDEA_DATABASE_PASSWORD=root
    ports:
      - "3000:3000"
    depends_on:
      - dios-database
    networks:
      - dios
      - dios-aldea
      - dios-cuenta
      - dios-kong

volumes:
  dios:
    external:
      name: neeco_dios

networks:
  dios:
    external:
      name: neeco_dios
  dios-aldea:
    external:
      name: neeco_dios-aldea
  dios-cuenta:
    external:
      name: neeco_dios-cuenta
  dios-kong:
    external:
      name: neeco_dios-kong
