version: '2'
services:
  dios-database:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: dios_development
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dios:/var/lib/mysql
    networks:
      - neeco
  dios-application:
    image: registry.neec.xyz/dev/dios-application:latest
    environment:
      DIOS_PORT: 3000
      DIOS_DATABASE_HOST: dios-database
      DIOS_DATABASE_USER: root
      DIOS_DATABASE_PASSWORD: root
      DIOS_SECRET_KEY_BASE: x
      KONG_URL: http://kong-application:8001/
      IMAGEN_URL: http://imagen-application:8000/
      CAJA_DATABASE_HOST: caja-database
      CAJA_DATABASE_USER:
      CAJA_DATABASE_PASSWORD:
      CUENTA_DATABASE_HOST: cuenta-database
      CUENTA_DATABASE_USER:
      CUENTA_DATABASE_PASSWORD:
      ALDEA_DATABASE_HOST: aldea-database
      ALDEA_DATABASE_USER:
      ALDEA_DATABASE_PASSWORD:
      RAILS_ENV: development
    depends_on:
      - dios-database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - neeco

volumes:
  dios:
    driver: local

networks:
  neeco:
    external:
      name: neeco_develop
