version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql
      - /app/log
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes_from:
      - datastore
    ports:
      - "3306:3306"
  application:
    build: .
    image: dios-application
    environment:
      - RAILS_ENV=production
      - DIOS_PORT=3000
      - DIOS_DATABASE_HOST=database
      - DIOS_DATABASE_USER=root
      - DIOS_DATABASE_PASSWORD=root
      - DIOS_DATABASE_PORT=3306
      - DIOS_SECRET_KEY_BASE=1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
      - CUENTA_DATABASE_HOST=database
      - CUENTA_DATABASE_USER=root
      - CUENTA_DATABASE_PASSWORD=root
      - CUENTA_DATABASE_PORT=13306
      - ALDEA_DATABASE_HOST=database
      - ALDEA_DATABASE_USER=root
      - ALDEA_DATABASE_PASSWORD=root
      - ALDEA_DATABASE_PORT=23306
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes_from:
      - datastore
