# MySQL. Versions 5.0 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DIOS_DATABASE_USER'] || "root" %>
  password: <%= ENV['DIOS_DATABASE_PASSWORD'] || "" %>
  host: <%= ENV['DIOS_DATABASE_HOST'] || "127.0.0.1" %>

development:
  <<: *default
  database: dios_development

test:
  <<: *default
  database: dios_test

production:
  <<: *default
  database: dios_production

caja:
  database: caja_production
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['CAJA_DATABASE_USER'] %>
  password: <%= ENV['CAJA_DATABASE_PASSWORD'] %>
  host: <%= ENV['CAJA_DATABASE_HOST'] %>

cuenta:
  database: cuenta_prod
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['CUENTA_DATABASE_USER'] %>
  password: <%= ENV['CUENTA_DATABASE_PASSWORD'] %>
  host: <%= ENV['CUENTA_DATABASE_HOST'] %>

aldea:
  database: aldea_production
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['ALDEA_DATABASE_USER'] %>
  password: <%= ENV['ALDEA_DATABASE_PASSWORD'] %>
  host: <%= ENV['ALDEA_DATABASE_HOST'] %>
